name: Sync Docs to Confluence
on:
  push:
  # schedule:
  #   # Runs on Mondays at 8:55 Central
  #   - cron: 55 13 * * 1
jobs:
  clear-docs:
    runs-on: ubuntu-latest
    steps:
      - run: |
        h1="Authorization: Basic $(echo -n $JIRA_USER:$JIRA_API_TOKEN | base64)"
        h2="Content-Type: application/json"
        curl -X GET -H "$h1" -H "$h2" "https://packback.atlassian.net/wiki/rest/api/content/1242529793/child/page?limit=1000" | \
          jq -re '.results[].id'
  # sync-docs:
  #   runs-on: ubuntu-latest
  #   needs: clear-docs
  #   steps:
  #     - run: ./make.sh sync_markdown_to_confluence