name: Sync Docs to Confluence
on:
  push:
  # schedule:
  #   # Runs on Mondays at 8:55 Central
  #   - cron: 55 13 * * 1
jobs:
  clear-docs:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      - run: ./make.sh clear_confluence
  # sync-docs:
  #   runs-on: ubuntu-latest
  #   needs: clear-docs
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: ./make.sh sync_markdown_to_confluence