name: Sync Docs to Confluence
on:
  push:
  # schedule:
  #   # Runs on Mondays at 8:55 Central
  #   - cron: 55 13 * * 1
jobs:
  # clear-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Check out code using git
  #     - name: Checkout to Branch
  #       uses: actions/checkout@v2
  #     - name: Delete existing docs from Confluence
  #       run: ./scripts/clear.sh
  #       env:
  #         JIRA_USER: ${{ secrets.JIRA_USER }}
  #         JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  sync-docs:
    runs-on: ubuntu-latest
    container: kovetskiy/mark
    # needs: clear-docs
    steps:
      - name: Checkout to Branch
        uses: actions/checkout@v2
      - run: ls
      - name: Sync docs to Confluence
        run: ./scripts/sync.sh
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}