name: Sync Docs to Confluence
on:
  push:
  # schedule:
  #   # Runs on Mondays at 8:55 Central
  #   - cron: 55 13 * * 1
jobs:
  clear-docs:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      - run: ./scripts/clear.sh
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  sync-docs:
    runs-on: kovetskiy/mark
    needs: clear-docs
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/sync.sh
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}